services:
#  nginx:
#    image: nginx:1.23.3
#    volumes:
#      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    depends_on:
#      - fastapi_service
#    networks:
#      - yandex_network
#    ports:
#      - "80:80"

  auth_service:
    build:
      context: ./flask_app
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - yandex_network

  postgres:
    image: postgres:13
    volumes:
      - ./pg_data/:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - yandex_network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
#
#  redis:
#    image: redis:7.0.8
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    networks:
#      - yandex_network
#    volumes:
#      - ../redis_data:/data
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 1s
#      timeout: 3s
#      retries: 30
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
#    ports:
#      - "6379:6379"

networks:
    yandex_network:
